### ISSUE TITLE
Add loongarch architecture support 

### ISSUE THREAD

**Issue by jinqingchen-uniontech** [openSUSE/hwinfo#101]
I added loongarch architecture support in the src/hd/hd.c file, please submit me the upstream permissions

**Comment by jinqingchen-uniontech** [comment]
If you have time, please reply me, I will be very grateful

**Comment by wfeldt** [comment]
What's the matter?

**Comment by jinqingchen-uniontech** [comment]
I added loongarch architecture support in the src/hd/hd.c file,Allow me to submit to you the upstream

**Comment by wfeldt** [comment]
That's been merged.

**Comment by jinqingchen-uniontech** [comment]
I'm sorry. I just saw it. Thank you very much！！
