### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [openSUSE/hwinfo#13]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) ⇒ [do_scan](https://github.com/openSUSE/hwinfo/blob/43ea1db3cb8ea89bf7b4bb6b098cedcb7708b089/hwscan.c#L286)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [do_hw](https://github.com/openSUSE/hwinfo/blob/43ea1db3cb8ea89bf7b4bb6b098cedcb7708b089/hwinfo.c#L497)

**Comment by wfeldt** [comment]
No, please don't.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would it be a bit safer to [detect every error situation as early as possible](https://github.com/openSUSE/hwinfo/blob/caeb9044b083ebec975888f6a5b57f63731dcfd5/hwscan.c#L397 "Update candidate: do_show()")?
