### ISSUE TITLE
Critique on your examples using hwinfo

### ISSUE THREAD

**Issue by reanimastudios** [openSUSE/hwinfo#65]
I'm not quite sure devs do this constantly, but 

$hwinfo --gfxcard won't produce any results.

You must be either accessing root directly [a no-no] or use the sudo command.

**Comment by wfeldt** [comment]
No, this does not require root. Can you send me an example where it matters? Run `hwinfo --gfxcard --log=foo.log`. Both as root and as normal user. I'd like to have a look at these logs.

**Comment by daniel-mueller** [comment]
I can confirm that I have to run hwinfo with sudo on  a recent installation of Leap 15.

```bash
ll /usr/sbin/ | grep hwinfo
-rwxr-xr-x 1 root root      38K 22. Apr 21:38 hwinfo
```

**Comment by wfeldt** [comment]
I'm using Leap 15.0 myself and it works as expected. Please provide the logs as described above,

**Comment by daniel-mueller** [comment]
Without sudo (no log file generated):
    hwinfo --gfxcard --log=foo.txt
                  
    Das Programm 'hwinfo' ist verfügbar im Paket 'hwinfo', das auf ihrem System installiert ist.
    
    Der absolute Pfad für 'hwinfo' ist '/usr/sbin/hwinfo', daher kann das Programm möglicherweise nur    von Benutzern mit Superuser-Rechten gestartet werden (z. B. root).

With sudo:
[foo.txt](https://github.com/openSUSE/hwinfo/files/2160932/foo.txt)

**Comment by wfeldt** [comment]
> Without sudo (no log file generated)

That's impossible. It must contain *something*. Is the directory writable?

> Das Programm 'hwinfo' ist verfügbar im Paket 'hwinfo', ...

Where does this come from?

**Comment by daniel-mueller** [comment]
Here is what I am doing (/bin/bash this time):
![screenshot_20180704_214357](https://user-images.githubusercontent.com/3153932/42292579-cf488d40-7fd3-11e8-8e31-a59340ca0ec0.png)

On a sidenote: This is not the first time I encountered the message telling my about absolute path and permissions of an executable. So I guess it's not specific to hwinfo.

**Comment by wfeldt** [comment]
My suspicion is that there is some tool spinning out those weird 'helpful' messages but in effect
not executing hwinfo at all.

You you try running it with full path, like `/usr/sbin/hwinfo --gfxcard`?

**Comment by daniel-mueller** [comment]
Yes, seems like /usr/sbin is not in $PATH by default and zypper tries to help. Thank you!
