### ISSUE TITLE
--framebuffer does not list modes

### ISSUE THREAD

**Issue by debdog** [openSUSE/hwinfo#82]
It prints everything up to "Memory Range:" then omits the "Mode" lines and then prints the "Config Status:" line.
Tested on versions 21.67 (compiled from source) and 21.63 (Debian Buster package).
Last version that I am aware of that works is 21.38 (Debian Stretch package).

```
# hwinfo --version
21.67
# hwinfo --framebuffer
02: None 00.0: 11001 VESA Framebuffer                           
  [Created at bios.459]
  Unique ID: rdCR._RYrDVnUxd7
  Hardware Class: framebuffer
  Model: "(C) 1988-2005, ATI RS690"
  Vendor: "(C) 1988-2005, ATI Technologies Inc."
  Device: "RS690"
  SubVendor: "ATI ATOMBIOS"
  SubDevice: 
  Revision: "01.00"
  Memory Size: 16 MB
  Memory Range: 0x00000000-0x00ffffff (rw)
  Config Status: cfg=new, avail=yes, need=no, active=unknown

```

**Comment by wfeldt** [comment]
I added some restrictions to avoid crashes on some systems:

- https://github.com/openSUSE/hwinfo/pull/47
- https://github.com/openSUSE/hwinfo/pull/49

around 21.43.

If you have the full log (`hwinfo --framebuffer --log=foo.log`) I can have a look.

**Comment by debdog** [comment]
Thanks for looking into that, really appreciate it! If you need more info or something, I'd be glad to provide
[hwinfo-21.67_frambuffer.log](https://github.com/openSUSE/hwinfo/files/3445341/hwinfo-21.67_frambuffer.log)
 it.

**Comment by wfeldt** [comment]
It gets the video mode list but fails to read individual mode details.

Could you try https://github.com/wfeldt/mdt? Just run `make` to get a small tool `mdt`. It's basically the video mode stuff from hwinfo but as a separate tool with more debugging output.

You'll also need https://github.com/wfeldt/libx86emu for it.

Does `mdt --modes` work for you? And also `mdt --modes --no-io`?

**Comment by debdog** [comment]
I'm sorry to report mdt does not compile here: [make_mdt.log](https://github.com/openSUSE/hwinfo/files/3446607/make_mdt.log)
I am still on Devuan ASCII (Debian Stretch) and am prolly not up-to-date software wise. gcc version is 6.3.0 20170516. But I have a system here on which I could upgrade, if required.

Tried with libx86emu from your link (compiled fine) and the Debian package libx86emu-dev with exactly the same outcome.
https://packages.debian.org/stretch/libx86emu-dev

**Comment by wfeldt** [comment]
This is ok, you need only `mdt` and that compiled fine.

**Comment by debdog** [comment]
Haha, oopsie.

```
./mdt --modes
video bios: using int 0x10
version = 3.0, oem version = 15.48
memory = 16384k
oem name [0xc026c] = "AMD ATOMBIOS"
vendor name [0xc0178] = "(C) 1988-2010, Advanced Micro Devices, Inc."
product name [0xc0107] = "BONAIRE"
product revision [0xc4d18] = "01.00"
29 video modes:
  0x0100[bb]: 640x400+640, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0101[bb]: 640x480+640, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0103[bb]: 800x600+832, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0105[bb]: 1024x768+1024, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0107[bb]: 1280x1024+1280, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0110[bb]: 640x480+1280, 15+1 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0111[bb]: 640x480+1280, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0113[bb]: 800x600+1664, 15+1 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0114[bb]: 800x600+1664, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0116[bb]: 1024x768+2048, 15+1 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0117[bb]: 1024x768+2048, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0119[bb]: 1280x1024+2560, 15+1 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x011a[bb]: 1280x1024+2560, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0163[bb]: 1280x960+1280, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0165[bb]: 1280x960+2560, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0166[bb]: 1280x960+5120, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0121[bb]: 640x480+2560, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0122[bb]: 800x600+3328, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0123[bb]: 1024x768+4096, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0124[bb]: 1280x1024+5120, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0143[bb]: 1400x1050+1408, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0145[bb]: 1400x1050+2816, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0146[bb]: 1400x1050+5632, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0173[ba]: 1600x1200+1600, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0175[ba]: 1600x1200+3200, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x0176[ba]: 1600x1200+6400, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x01d1[bb]: 1920x1080+1920, 8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x01d2[bb]: 1920x1080+3840, 16 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
  0x01d4[bb]: 1920x1080+7680, 24+8 bpp, max. 400 MHz, fb: 0xc0000000, a0000.7: 64k
```

```
./mdt --modes --no-io
video bios: using int 0x10
version = 3.0, oem version = 15.48 
memory = 16384k
oem name [0xc026c] = "AMD ATOMBIOS"
vendor name [0xc0178] = "(C) 1988-2010, Advanced Micro Devices, Inc."
product name [0xc0107] = "BONAIRE" 
product revision [0xc4d18] = "01.00"
26 video modes:
  0x0100: no mode info
  0x0101: no mode info
  0x0103: no mode info
  0x0105: no mode info
  0x0107: no mode info
  0x0110: no mode info
  0x0111: no mode info
  0x0113: no mode info
  0x0114: no mode info
  0x0116: no mode info
  0x0117: no mode info
  0x0119: no mode info
  0x011a: no mode info
  0x0163: no mode info
  0x0165: no mode info
  0x0166: no mode info
  0x0121: no mode info
  0x0122: no mode info
  0x0123: no mode info
  0x0124: no mode info
  0x0143: no mode info
  0x0145: no mode info
  0x0146: no mode info
  0x0173: no mode info
  0x0175: no mode info
  0x0176: no mode info
```
Looks good, I suppose.

**Comment by wfeldt** [comment]
Ok, this is going to get tricky. Could you pick a mode (say 0x176) and run

`mdt --mode 0x176 --show dump,dump.mem.acc,io` and the same also with `--no-io` added?

This logs most of the memory and io interaction and hopefully this gets us some hint.

**Comment by debdog** [comment]
[mdt_0x176.txt](https://github.com/openSUSE/hwinfo/files/3482488/mdt_0x176.txt)
[mdt_0x176_noio.txt](https://github.com/openSUSE/hwinfo/files/3482489/mdt_0x176_noio.txt)
Would it help if I ran this on different PCs?

**Comment by wfeldt** [comment]
Ok, after thinking about this for a while: I see no good solution here.

The video bios wants to get some state info from the gfx card. Maybe it wants to check the availability of the individual modes. Which means you have to do some level of gfx card emulation (which is out of scope) or turn io access on again (also no way).

Which leaves the possibility to either add an option to hwinfo (like `--enable-io`) or use the `hwprobe` environment var (like `hwprobe=+io`). The latter is less obvious but has the advantage that you can add it to the kernel command line and it will always be taken into account.

Problem is, I'm not sure if this is really worth it.

**Comment by debdog** [comment]
TBH I have no clue what you're talking about. Just a simple user here. Have been using hwinfo to determine the mode to tell the bootloader to use for 'bout 20 years now. I can live with using mdt instead (as long as it compiles) it'd just be sad.
Anyhow, thanks a lot for looking into the issue!
Griaßla

**Comment by wfeldt** [comment]
Over the time, there were many bug reports that mode detection interferes with the regular graphics card operation (the X server). So in the end I decided to turn off gfx card memory and port access in the emulation code so no harm can come to your graphical desktop.

For most of the cards this is sufficient to read the mode list as they basically just return a pointer to some memory area. But some want to have a look at their internal state before they hand out data. This of course fails as the emulation does not access the real card at all. And you get no or incomplete data, as in your case.

I cannot re-enable real hardware access unconditionally due to this. But adding some option to hwinfo would be ok.

**Comment by debdog** [comment]
I get it now, thanks! If I disable the display manager and boot into tty1 (as I usually do except with this one laptop where I encountered the issue) --framebuffer works as expected. And that's all I need. So, from my point of view, there is no need to change anything.
Once again, thanks a lot!

**Comment by debdog** [comment]
On second thought, one thing might benefit from a tiny alteration. Here's a proposal: 
[hwinfo.8.patch.txt](https://github.com/openSUSE/hwinfo/files/3534218/hwinfo.8.patch.txt)
