### ISSUE TITLE
How long build time of ./check_hd --check --sort --cfile hd_ids ?

### ISSUE THREAD

**Issue by youling257** [openSUSE/hwinfo#83]
./check_hd --check --sort --cfile hd_ids.h src/bus src/class src/extra src/special src/scanner src/network src/usb src/usb2 src/isapnp src/monitor src/camera src/tv2 src/tv src/dvb2 src/dvb src/chipcard src/modem src/pcmcia src/s390 src/sdio src/x11.i386 src/modem.i386 src/pci src/storage src/sound src/mouse src/braille

check_hd progress running 30 minute.

**Comment by youling257** [comment]
build complete.

**Comment by wfeldt** [comment]
Yes, the internal db creation algorithm scales very badly and it may take a few minutes to run even on a fast machine. :-(

**Comment by sebma** [comment]
@wfeldt I have an old Asus b206 with an Intel Atom N270 (1.6GHz) and 2GiB of RAM running XFCE.

It sure takes more than 30 minutes to proceed.

Can I comment this build step in the ../blob/master/src/ids/Makefile to skip it or is this database really necessary for hwinfo ?

**Comment by wfeldt** [comment]
Either removing `--check` or adding `-no-compact`  would make it build much faster, I think:

https://github.com/openSUSE/hwinfo/blob/master/src/ids/Makefile#L59

**Comment by WeychonOnGitHub** [comment]
In fact do not worry, I've tried it in Gentoo on a aarch64 machine, and it has lasted for almost 20 min and haven't been done till I'm still waiting.
